import { HeroUIProvider } from '@heroui/react';

import '@/app/styles';

export const metadata = {
  title: 'CAMUS',
  // description: 'Generated by Next.js',
  icons: {
    icon: '/images/logo.svg',
  },
};

const RootLayout = ({ children }: { children: ReactNode }) => {
  return (
    <html lang='en'>
      <body>
        <HeroUIProvider className='flex min-h-screen w-screen flex-col'>
          {children}
        </HeroUIProvider>
      </body>
    </html>
  );
};

export default RootLayout;
